### ISSUE TITLE
sorting does not preserves empty line at EOF

### ISSUE THREAD

**Issue by zafarella** [doshprompt/grunt-json-sort#1]
defined as:

```
sortJSON:
      src: "<%= yeoman.app %>/i18n/*.json"
      options:
        spacing: 2
```

Sorts the json, however it truncates the last empty line in the file, which is uncomfortable when using diffs in something like github especially in collaborative environment.
What you get is those json files always getting in the change list even though you didn't modified them.

The sorting should not remove last empty line in files. Or add an option.
